test_execution_failure.byte: Failure: This error was triggered on purpose.
